run_name: "HER_bitflip"
with_her: True
env: "bitflip"
n_bits: 25 #45 #25 #10  # nbits [10, 25, 45] are tested. You should change max_episode_steps to the same value of n_bits when you change n_bits option.
n_episodes: 1000000 #20000
seed: 1234
log_video: True
log_every: 10
save_every: 100
max_episode_steps: 25 #45 #25 #10 
model_basedir: "./checkpoints"
model_ckpt: "./checkpoints/bitflip/HER_bitflip/20230416191548/best_score_25bit.ckpt"

optimizer: "Adam"
learning_rate: 
  policy: 0.0001

discount: 0.99
eps_high: 0.9
eps_low: 0.05
eps_decay: 200

batch_size: 1024
buffer_size: 1000000
start_size: 10 #100
hidden_layer: 2
hidden_units: 256 #128
non_linearity: "ReLU"
target_smoothing_coefficient: 0.005
